create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name varchar(5) not null check (char_length(name) between 1 and 5),
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

drop policy if exists "Allow read scores" on public.scores;
create policy "Allow read scores"
  on public.scores
  for select
  to anon
  using (true);

drop policy if exists "Allow insert scores" on public.scores;
create policy "Allow insert scores"
  on public.scores
  for insert
  to anon
  with check (true);

